name: "Nix Cache"
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: parkfuchs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: "result-parkfuchs"
      - run: |
          nix build .#parkfuchs -o result-parkfuchs
